### ISSUE TITLE
remove the max_stack = 1  

### ISSUE THREAD

**Issue by crazyginger72** [VanessaE/homedecor_modpack#120]
ok i think it needs to be removed as its a pita if your doing a shop or building tons of them into a room

**Comment by LazyJ** [comment]
I"ll toss in my two-cents.

At present, "stack_max = 1" is used in each of the lrfurn mod's items and homedecor/misc-nodes.lua:1258 *(but that's for the books which, due to their text content being unique to each book, should be one book per inventory slot)*.

Living Room Furniture's armchairs, coffeetable, endtable, longsofas, and sofas are all set to limit one item per inventory slot. It would be more space-efficient in the inventory if lrfrun's items would stack like default items do, i.e. 5 longsofas in 1 inventory slot. Between recipe items and furnishings and other interior decorations, the inventory can fill up very quickly when working on the interior of shopping malls, apartment buildings, office buildings,... anything larger than a hut.
