### ISSUE TITLE
Signs_lib crops higer-res fonts

### ISSUE THREAD

**Issue by Pilcrow182** [VanessaE/homedecor_modpack#283]
![Cropped Text](http://i.imgur.com/AFIRjiy.png)
Signs_lib seems to work fine when using the default textures and smaller, but when using the larger textures included in the extra_fonts folder, the bottom part of the line is chopped off. Shown above is the 34px font, but 25px displays similarly.

**Comment by kaeza** [comment]
signs_lib caches character sizes in `<world>/signs_lib_chardb`. See if deleting that file (so it gets recreated) fixes the problem.

**Comment by Pilcrow182** [comment]
nope, deleting signs_lib_chardb from my world didn't change the clipping/cropping issue.

**Comment by kaeza** [comment]
After some tests, I found the problem: It's not that the text gets cut off, but that the texture used as "background" to implement colors is not big enough to fill the whole line, only the top 16 pixels.

Fixed by 503e2fcc5fd2e1e346b87cf6a2b90dd703218d2d and 18ba3d75e7f60eea505606baea9ba1164c472178.

Thank you for reporting!

**Comment by kaeza** [comment]
Sorry, those last commits fucked up everything (see #285).
Fixed again in 5156e2141f8972c89480c60d12e88af446571aef, this time for real.
