### ISSUE TITLE
Expansion code doesn't handle nodes forced into otherwise-occupied spaces (upper parts of doors, etc)

### ISSUE THREAD

**Issue by LeMagnesium** [VanessaE/homedecor_modpack#292]
Works with `homedecor:glass_door_left`.
If you place a single node door (one node covering two spaces) and sneak to the top of it, you can place a node inside the top part of the door by pressing the sneak key and right-clicking the top part of the selection box. The main problem with that is that the door will remove (even if it's normal that it does) this node when updating after a right click.
So far, to fix that, I've implemented a drop mechanism if the node inside the top part is not air, but I don't think it's the best idea possible, so I let you know that this bug is still present.

![Door placed](https://lut.im/rXGULNdO/IKLt47ei)

![Sneak to the top](https://lut.im/Z20YeWso/clDk3MZs)

![Cobble placed](https://lut.im/v7OD4Drk/aF6JldZK)

![Vanished?](https://lut.im/wCQJpFb0/VSNNhbXe)

**Comment by VanessaE** [comment]
Yeah, I'm aware that this happens (sofas and spiral staircases can also have this happen), but it's not a bug in Home Decor, per se.  The doors are mesh models that happen to occupy two node spaces, but the engine only knows how to evaluate the node space the model "starts" in (in this case, the bottom part of the door).

There's been some discussion of how to make the engine deal with this properly, but to my knowledge nothing related has been implemented yet.

In any case, I don't see the need for the "drop" idea you had; rather, some tweaks to the "expansion" code are probably needed to handle this sort of condition. If the user wants to force something into the otherwise-apparently-occupied space until then, it's their fault if it gets deleted. :stuck_out_tongue_winking_eye:

**Comment by kaeza** [comment]
A simple workaround would be to create a "door top" node that is placed on top of the bottom part, but it is invisible itself (transparent texture/small nodebox/whatever), and make this top node not `buildable_to`. At least this will prevent node placement (which can cause loss of important/expensive/hard-to-get nodes on door right-click overwrite).

**Comment by t4im** [comment]
The reason we didn't do that back then, was because it left unuseble/unbuildable nodes when the expanded nodes where being screwdriver rotated.
But as i just saw, over the last half year an `on_rotate()` callback was added, so we could revisit that.

**Comment by t4im** [comment]
Note, that doors (other than the japanese one) are still excepted to the fix by #294 due to needing a rewrite first to make use of the registration and expansion handling system, but will _then_ be protecting "air space" as well.
